name: lab_tests
on: push
jobs:
   run-test:
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: actions/setup-python@v3
        with:
        python-version: '3.x'

      - name: Install libraries
        uses: pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test

   deploy: 
      needs: run-test
      runs-on: ubbunto

      steps:
            -name: checkout
             uses:actions/checkout@v4

            -name: finishDiploy
             uses: ech $ "deploying finished"
